services:
  psn_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psn_service
    volumes:
      - ./src:/app/src
    ports:
      - "8001:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      # Add any other environment variables your service needs
    restart: unless-stopped
    networks:
      - ovhl_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  ovhl_network:
    driver: bridge