from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'ForumPost',
    'ForumReaction',
    'ForumFollower',
    'ForumPostSubscription',
    'ForumComment',
    'League',
    'LeagueSeason',
    'Conference',
    'Division',
    'Season',
    'LeagueCommissioner',
    'LeagueBOG',
    'Match',
    'ClubMatchStats',
    'ClubMatchStatsDetails',
    'CustomKit',
    'ClubAggregateMatchStats',
    'MatchAnalytics',
    'PlayerMatch',
    'PlayerSeason',
    'PlayerTeamSeason',
    'PlayerLeagueHistory',
    'PSNProfile',
    'PSNAvatar',
    'PSNTrophy',
    'PSNGame',
    'PSNSyncLog',
    'PSNGameTrophies',
    'Team',
    'TeamSeason',
    'TeamManager',
    'Bid',
    'Contract',
    'User',
    'EaIdHistory',
    'SystemHistory',
    'GamertagHistory',
    'Notification',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'ForumPost': {
        'author': 'User',
        'comments': 'ForumComment',
        'reactions': 'ForumReaction',
        'followers': 'ForumFollower',
        'subscribers': 'ForumPostSubscription',
    },
    'ForumReaction': {
        'user': 'User',
        'post': 'ForumPost',
        'comment': 'ForumComment',
    },
    'ForumFollower': {
        'user': 'User',
        'post': 'ForumPost',
    },
    'ForumPostSubscription': {
        'user': 'User',
        'post': 'ForumPost',
    },
    'ForumComment': {
        'author': 'User',
        'post': 'ForumPost',
        'quotedComment': 'ForumComment',
        'quotedBy': 'ForumComment',
        'reactions': 'ForumReaction',
    },
    'League': {
        'parentLeague': 'League',
        'subLeagues': 'League',
        'conferences': 'Conference',
        'divisions': 'Division',
        'teams': 'Team',
        'seasons': 'LeagueSeason',
    },
    'LeagueSeason': {
        'league': 'League',
        'season': 'Season',
        'commissioners': 'LeagueCommissioner',
        'bogs': 'LeagueBOG',
        'teams': 'TeamSeason',
        'playerHistory': 'PlayerLeagueHistory',
    },
    'Conference': {
        'league': 'League',
        'divisions': 'Division',
    },
    'Division': {
        'conference': 'Conference',
        'league': 'League',
        'teams': 'Team',
    },
    'Season': {
        'leagueSeasons': 'LeagueSeason',
        'players': 'PlayerSeason',
    },
    'LeagueCommissioner': {
        'user': 'User',
        'leagueSeason': 'LeagueSeason',
    },
    'LeagueBOG': {
        'user': 'User',
        'leagueSeason': 'LeagueSeason',
    },
    'Match': {
        'teamSeason': 'TeamSeason',
        'clubMatchStats': 'ClubMatchStats',
        'playerStats': 'PlayerMatch',
        'clubAggregateMatchStats': 'ClubAggregateMatchStats',
        'matchAnalytics': 'MatchAnalytics',
        'playerSeasons': 'PlayerSeason',
    },
    'ClubMatchStats': {
        'details': 'ClubMatchStatsDetails',
        'match': 'Match',
    },
    'ClubMatchStatsDetails': {
        'customKit': 'CustomKit',
        'clubMatchStats': 'ClubMatchStats',
    },
    'CustomKit': {
        'details': 'ClubMatchStatsDetails',
    },
    'ClubAggregateMatchStats': {
        'match': 'Match',
    },
    'MatchAnalytics': {
        'match': 'Match',
    },
    'PlayerMatch': {
        'match': 'Match',
        'playerTeamSeason': 'PlayerTeamSeason',
        'playerSeason': 'PlayerSeason',
    },
    'PlayerSeason': {
        'user': 'User',
        'season': 'Season',
        'contract': 'Contract',
        'teamSeasons': 'PlayerTeamSeason',
        'leagueHistory': 'PlayerLeagueHistory',
        'playerMatches': 'PlayerMatch',
        'matches': 'Match',
    },
    'PlayerTeamSeason': {
        'playerSeason': 'PlayerSeason',
        'rosterTeam': 'TeamSeason',
        'trainingCampTeam': 'TeamSeason',
        'inactiveTeam': 'TeamSeason',
        'playerMatches': 'PlayerMatch',
    },
    'PlayerLeagueHistory': {
        'playerSeason': 'PlayerSeason',
        'leagueSeason': 'LeagueSeason',
    },
    'PSNProfile': {
        'user': 'User',
        'avatars': 'PSNAvatar',
        'trophySummary': 'PSNTrophy',
        'games': 'PSNGame',
        'syncLogs': 'PSNSyncLog',
        'gameTrophies': 'PSNGameTrophies',
    },
    'PSNAvatar': {
        'profile': 'PSNProfile',
    },
    'PSNTrophy': {
        'profile': 'PSNProfile',
    },
    'PSNGame': {
        'profile': 'PSNProfile',
        'trophyInfo': 'PSNGameTrophies',
    },
    'PSNSyncLog': {
        'profile': 'PSNProfile',
    },
    'PSNGameTrophies': {
        'profile': 'PSNProfile',
        'game': 'PSNGame',
    },
    'Team': {
        'league': 'League',
        'division': 'Division',
        'seasons': 'TeamSeason',
        'nhlAffiliate': 'Team',
        'ahlAffiliate': 'Team',
        'ahlAffiliates': 'Team',
        'echlAffiliates': 'Team',
    },
    'TeamSeason': {
        'team': 'Team',
        'leagueSeason': 'LeagueSeason',
        'matches': 'Match',
        'rosterPlayers': 'PlayerTeamSeason',
        'trainingCampPlayers': 'PlayerTeamSeason',
        'inactivePlayers': 'PlayerTeamSeason',
        'bids': 'Bid',
        'managers': 'TeamManager',
    },
    'TeamManager': {
        'user': 'User',
        'teamSeason': 'TeamSeason',
    },
    'Bid': {
        'contract': 'Contract',
        'teamSeason': 'TeamSeason',
    },
    'Contract': {
        'playerSeason': 'PlayerSeason',
        'bids': 'Bid',
    },
    'User': {
        'notifications': 'Notification',
        'forumPosts': 'ForumPost',
        'forumComments': 'ForumComment',
        'forumReactions': 'ForumReaction',
        'forumFollowing': 'ForumFollower',
        'forumSubscriptions': 'ForumPostSubscription',
        'eaIdHistory': 'EaIdHistory',
        'systemHistory': 'SystemHistory',
        'gamertags': 'GamertagHistory',
        'leagueCommissioners': 'LeagueCommissioner',
        'leagueBogs': 'LeagueBOG',
        'activeSeasons': 'PlayerSeason',
        'teamManagement': 'TeamManager',
        'psnProfile': 'PSNProfile',
    },
    'EaIdHistory': {
        'user': 'User',
    },
    'SystemHistory': {
        'user': 'User',
    },
    'GamertagHistory': {
        'user': 'User',
    },
    'Notification': {
        'user': 'User',
    },
}

# fmt: on