from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Player',
    'GamertagHistory',
    'Season',
    'Tier',
    'Team',
    'TeamSeason',
    'PlayerSeason',
    'PlayerTierHistory',
    'PlayerTeamSeason',
    'Contract',
    'Bid',
    'Match',
    'PlayerMatch',
    'Notification',
    'ForumPost',
    'ForumReaction',
    'ForumFollower',
    'ForumPostSubscription',
    'ForumComment',
    'TeamManager',
    'PSNProfile',
    'PSNAvatar',
    'PSNTrophy',
    'PSNGame',
    'PSNSyncLog',
    'PSNGameTrophies',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'player': 'Player',
        'notifications': 'Notification',
        'forumPosts': 'ForumPost',
        'forumComments': 'ForumComment',
        'forumReactions': 'ForumReaction',
        'forumFollowing': 'ForumFollower',
        'forumSubscriptions': 'ForumPostSubscription',
        'teamManagement': 'TeamManager',
        'psnProfile': 'PSNProfile',
    },
    'Player': {
        'user': 'User',
        'gamertags': 'GamertagHistory',
        'seasons': 'PlayerSeason',
    },
    'GamertagHistory': {
        'player': 'Player',
    },
    'Season': {
        'tiers': 'Tier',
        'players': 'PlayerSeason',
    },
    'Tier': {
        'season': 'Season',
        'teams': 'TeamSeason',
        'playerHistory': 'PlayerTierHistory',
    },
    'Team': {
        'seasons': 'TeamSeason',
        'managers': 'TeamManager',
        'nhlAffiliate': 'Team',
        'ahlAffiliate': 'Team',
        'ahlAffiliates': 'Team',
        'echlAffiliates': 'Team',
    },
    'TeamSeason': {
        'team': 'Team',
        'tier': 'Tier',
        'matches': 'Match',
        'players': 'PlayerTeamSeason',
        'bids': 'Bid',
    },
    'PlayerSeason': {
        'player': 'Player',
        'season': 'Season',
        'contract': 'Contract',
        'teamSeasons': 'PlayerTeamSeason',
        'tierHistory': 'PlayerTierHistory',
    },
    'PlayerTierHistory': {
        'playerSeason': 'PlayerSeason',
        'tier': 'Tier',
    },
    'PlayerTeamSeason': {
        'playerSeason': 'PlayerSeason',
        'teamSeason': 'TeamSeason',
        'matches': 'PlayerMatch',
    },
    'Contract': {
        'playerSeason': 'PlayerSeason',
        'bids': 'Bid',
    },
    'Bid': {
        'contract': 'Contract',
        'teamSeason': 'TeamSeason',
    },
    'Match': {
        'teamSeason': 'TeamSeason',
        'playerStats': 'PlayerMatch',
    },
    'PlayerMatch': {
        'match': 'Match',
        'playerTeamSeason': 'PlayerTeamSeason',
    },
    'Notification': {
        'user': 'User',
    },
    'ForumPost': {
        'author': 'User',
        'comments': 'ForumComment',
        'reactions': 'ForumReaction',
        'followers': 'ForumFollower',
        'subscribers': 'ForumPostSubscription',
    },
    'ForumReaction': {
        'user': 'User',
        'post': 'ForumPost',
        'comment': 'ForumComment',
    },
    'ForumFollower': {
        'user': 'User',
        'post': 'ForumPost',
    },
    'ForumPostSubscription': {
        'user': 'User',
        'post': 'ForumPost',
    },
    'ForumComment': {
        'author': 'User',
        'post': 'ForumPost',
        'quotedComment': 'ForumComment',
        'quotedBy': 'ForumComment',
        'reactions': 'ForumReaction',
    },
    'TeamManager': {
        'user': 'User',
        'team': 'Team',
    },
    'PSNProfile': {
        'user': 'User',
        'avatars': 'PSNAvatar',
        'trophySummary': 'PSNTrophy',
        'games': 'PSNGame',
        'syncLogs': 'PSNSyncLog',
        'gameTrophies': 'PSNGameTrophies',
    },
    'PSNAvatar': {
        'profile': 'PSNProfile',
    },
    'PSNTrophy': {
        'profile': 'PSNProfile',
    },
    'PSNGame': {
        'profile': 'PSNProfile',
        'trophyInfo': 'PSNGameTrophies',
    },
    'PSNSyncLog': {
        'profile': 'PSNProfile',
    },
    'PSNGameTrophies': {
        'profile': 'PSNProfile',
        'game': 'PSNGame',
    },
}

# fmt: on