import { AHLTeam, AHLDivision } from './types';

export const AHL_TEAMS: AHLTeam[] = [
  // Atlantic Division
  {
    id: 'ahl_bri',
    abbreviation: 'BRI',
    name: 'Bridgeport Islanders',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_nyi',
    echlTeamId: 'echl_wor',
    colors: {
      primary: '#00468B',
      secondary: '#F26924',
    },
    logo_path: '/team_logos/ahl/bridgeport-islanders.svg',
  },
  {
    id: 'ahl_cha',
    abbreviation: 'CHA',
    name: 'Charlotte Checkers',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_fla',
    echlTeamId: 'echl_sav',
    colors: {
      primary: '#E51A38',
      secondary: '#000000',
    },
    logo_path: '/team_logos/ahl/charlotte-checkers.svg',
  },
  {
    id: 'ahl_hfd',
    abbreviation: 'HFD',
    name: 'Hartford Wolf Pack',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_nyr',
    echlTeamId: 'echl_blm',
    colors: {
      primary: '#00548E',
      secondary: '#EF3E42',
    },
    logo_path: '/team_logos/ahl/hartford-wolf-pack.svg',
  },
  {
    id: 'ahl_her',
    abbreviation: 'HER',
    name: 'Hershey Bears',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_wsh',
    echlTeamId: 'echl_sc',
    colors: {
      primary: '#7E543A',
      secondary: '#472A2B',
    },
    logo_path: '/team_logos/ahl/hershey-bears.svg',
  },
  {
    id: 'ahl_lhv',
    abbreviation: 'LV',
    name: 'Lehigh Valley Phantoms',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_phi',
    echlTeamId: 'echl_rea',
    colors: {
      primary: '#F58220',
      secondary: '#000000',
    },
    logo_path: '/team_logos/ahl/lehigh-valley-phantoms.svg',
  },
  {
    id: 'ahl_pro',
    abbreviation: 'PRO',
    name: 'Providence Bruins',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_bos',
    echlTeamId: 'echl_mne',
    colors: {
      primary: '#FBB337',
      secondary: '#000000',
    },
    logo_path: '/team_logos/ahl/providence-bruins.svg',
  },
  {
    id: 'ahl_spr',
    abbreviation: 'SPR',
    name: 'Springfield Thunderbirds',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_stl',
    echlTeamId: 'echl_fla',
    colors: {
      primary: '#005CB9',
      secondary: '#041E41',
    },
    logo_path: '/team_logos/ahl/springfield-thunderbirds.svg',
  },
  {
    id: 'ahl_wbs',
    abbreviation: 'WBS',
    name: 'Wilkes-Barre/Scranton Penguins',
    conference: AHLConference.EASTERN,
    division: AHLDivision.ATLANTIC,
    nhlTeamId: 'nhl_pit',
    echlTeamId: 'echl_whl',
    colors: {
      primary: '#FEC23D',
      secondary: '#E31837',
    },
    logo_path: '/team_logos/ahl/wilkes-barre.svg',
  },

  // North Division
  {
    id: 'ahl_bel',
    abbreviation: 'BEL',
    name: 'Belleville Senators',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_ott',
    echlTeamId: 'echl_aln',
    colors: {
      primary: '#E3173E',
      secondary: '#000000',
    },
    logo_path: '/team_logos/ahl/belleville-senators.svg',
  },
  {
    id: 'ahl_cle',
    abbreviation: 'CLE',
    name: 'Cleveland Monsters',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_cbj',
    echlTeamId: 'echl_qc',
    colors: {
      primary: '#005695',
      secondary: '#FDBB30',
    },
    logo_path: '/team_logos/ahl/cleveland-monsters.svg',
  },
  {
    id: 'ahl_lav',
    abbreviation: 'LAV',
    name: 'Laval Rocket',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_mtl',
    echlTeamId: 'echl_tr',
    colors: {
      primary: '#001E61',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/ahl/laval-rocket.svg',
  },
  {
    id: 'ahl_roc',
    abbreviation: 'ROC',
    name: 'Rochester Americans',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_buf',
    echlTeamId: 'echl_jax',
    colors: {
      primary: '#393A87',
      secondary: '#DE2944',
    },
    logo_path: '/team_logos/ahl/rochester-americans.svg',
  },
  {
    id: 'ahl_syr',
    abbreviation: 'SYR',
    name: 'Syracuse Crunch',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_tbl',
    echlTeamId: 'echl_orl',
    colors: {
      primary: '#1D427C',
      secondary: '#AAA9AC',
    },
    logo_path: '/team_logos/ahl/syracuse-crunch.svg',
  },
  {
    id: 'ahl_tor',
    abbreviation: 'TOR',
    name: 'Toronto Marlies',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_tor',
    echlTeamId: 'echl_cin',
    colors: {
      primary: '#003E7E',
      secondary: '#FFC425',
    },
    logo_path: '/team_logos/ahl/toronto-marlies.svg',
  },
  {
    id: 'ahl_utc',
    abbreviation: 'UTC',
    name: 'Utica Comets',
    conference: AHLConference.EASTERN,
    division: AHLDivision.NORTH,
    nhlTeamId: 'nhl_njd',
    echlTeamId: 'echl_adk',
    colors: {
      primary: '#CF2031',
      secondary: '#000000',
    },
    logo_path: '/team_logos/ahl/utica-comets.svg',
  },

  // Central Division
  {
    id: 'ahl_chi',
    abbreviation: 'CHI',
    name: 'Chicago Wolves',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: "nhl_car",
    echlTeamId: 'echl_nf',
    colors: {
      primary: '#939283',
      secondary: '#E03A3E',
    },
    logo_path: '/team_logos/ahl/chicago-wolves.svg',
  },
  {
    id: 'ahl_gr',
    abbreviation: 'GR',
    name: 'Grand Rapids Griffins',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: 'nhl_det',
    echlTeamId: 'echl_tol',
    colors: {
      primary: '#866C3F',
      secondary: '#E51636',
    },
    logo_path: '/team_logos/ahl/grand-rapids-griffins.svg',
  },
  {
    id: 'ahl_ia',
    abbreviation: 'IA',
    name: 'Iowa Wild',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: 'nhl_min',
    echlTeamId: 'echl_ia',
    colors: {
      primary: '#144733',
      secondary: '#DFCAA3',
    },
    logo_path: '/team_logos/ahl/iowa-wild.svg',
  },
  {
    id: 'ahl_mb',
    abbreviation: 'MB',
    name: 'Manitoba Moose',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: 'nhl_wpg',
    echlTeamId: 'echl_nor',
    colors: {
      primary: '#041E41',
      secondary: '#A4A9AD',
    },
    logo_path: '/team_logos/ahl/manitoba-moose.svg',
  },
  {
    id: 'ahl_mil',
    abbreviation: 'MIL',
    name: 'Milwaukee Admirals',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: 'nhl_nsh',
    echlTeamId: 'echl_atl',
    colors: {
      primary: '#0E2B58',
      secondary: '#83C2EC',
    },
    logo_path: '/team_logos/ahl/milwaukee-admirals.svg',
  },
  {
    id: 'ahl_rkf',
    abbreviation: 'RKF',
    name: 'Rockford IceHogs',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: 'nhl_chi',
    echlTeamId: 'echl_ind',
    colors: {
      primary: '#DB1931',
      secondary: '#94959A',
    },
    logo_path: '/team_logos/ahl/rockford-icehogs.svg',
  },
  {
    id: 'ahl_tex',
    abbreviation: 'TEX',
    name: 'Texas Stars',
    conference: AHLConference.WESTERN,
    division: AHLDivision.CENTRAL,
    nhlTeamId: 'nhl_dal',
    echlTeamId: 'echl_idh',
    colors: {
      primary: '#1B6031',
      secondary: '#A5A6A8',
    },
    logo_path: '/team_logos/ahl/texas-stars.svg',
  },

  // Pacific Division
  {
    id: 'ahl_abb',
    abbreviation: 'ABB',
    name: 'Abbotsford Canucks',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_van',
    echlTeamId: 'echl_kal',
    colors: {
      primary: '#047835',
      secondary: '#0E1C2C',
    },
    logo_path: '/team_logos/ahl/abbotsford-canucks.svg',
  },
  {
    id: 'ahl_bak',
    abbreviation: 'BAK',
    name: 'Bakersfield Condors',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_edm',
    echlTeamId: 'echl_fw',
    colors: {
      primary: '#152342',
      secondary: '#DF4E10',
    },
    logo_path: '/team_logos/ahl/bakersfield-condors.svg',
  },
  {
    id: 'ahl_cgy',
    abbreviation: 'CAG',
    name: 'Calgary Wranglers',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_cgy',
    echlTeamId: 'echl_rc',
    colors: {
      primary: '#C2273D',
      secondary: '#F3BD48',
    },
    logo_path: '/team_logos/ahl/calgary-wranglers.svg',
  },
  {
    id: 'ahl_cv',
    abbreviation: 'CV',
    name: 'Coachella Valley Firebirds',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_sea',
    echlTeamId: 'echl_kc',
    colors: {
      primary: '#C8102E',
      secondary: '#FF681D',
    },
    logo_path: '/team_logos/ahl/coachella-valley-firebirds.png',
  },
  {
    id: 'ahl_col',
    abbreviation: 'COL',
    name: 'Colorado Eagles',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_col',
    echlTeamId: 'echl_uta',
    colors: {
      primary: '#FFD457',
      secondary: '#19398A',
    },
    logo_path: '/team_logos/ahl/colorado-eagles.svg',
  },
  {
    id: 'ahl_hnd',
    abbreviation: 'HND',
    name: 'Henderson Silver Knights',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_vgk',
    echlTeamId: 'echl_tah',
    colors: {
      primary: '#C2C4C6',
      secondary: '#B4975B',
    },
    logo_path: '/team_logos/ahl/henderson-silver-knights.svg',
  },
  {
    id: 'ahl_ont',
    abbreviation: 'ONT',
    name: 'Ontario Reign',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_lak',
    echlTeamId: 'echl_gvl',
    colors: {
      primary: '#A4A9AD',
      secondary: '#000000',
    },
    logo_path: '/team_logos/ahl/ontario-reign.svg',
  },
  {
    id: 'ahl_sd',
    abbreviation: 'SD',
    name: 'San Diego Gulls',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_ana',
    echlTeamId: 'echl_tul',
    colors: {
      primary: '#FF4C00',
      secondary: '#0083BF',
    },
    logo_path: '/team_logos/ahl/san-diego-gulls.svg',
  },
  {
    id: 'ahl_sj',
    abbreviation: 'SJ',
    name: 'San Jose Barracuda',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_sjs',
    echlTeamId: 'echl_wic',
    colors: {
      primary: '#266B73',
      secondary: '#DD8943',
    },
    logo_path: '/team_logos/ahl/san-jose-barracuda.svg',
  },
  {
    id: 'ahl_tuc',
    abbreviation: 'TUC',
    name: 'Tuscon Roadrunners',
    conference: AHLConference.WESTERN,
    division: AHLDivision.PACIFIC,
    nhlTeamId: 'nhl_uta',
    echlTeamId: 'echl_ala',
    colors: {
      primary: '#8E0A26',
      secondary: '#EEE2BE',
    },
    logo_path: '/team_logos/ahl/tucson-roadrunners.svg',
  },
];
