import {
  CHLTeam,
  CHLLeague,
  OHLDivision,
  QMJHLDivision,
  WHLDivision,
} from './types';

export const CHL_TEAMS: CHLTeam[] = [
  // OHL Teams
  // East Division
  {
    id: 'chl_ham',
    abbreviation: 'HAM',
    name: 'Brantford Bulldogs',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.EAST,
    colors: {
      primary: '#231F20',
      secondary: '#B47F3A',
    },
    logo_path: '/team_logos/chl/ohl/brantford-bulldogs.svg',
  },
  {
    id: 'chl_kgn',
    abbreviation: 'KGN',
    name: 'Kingston Frontenacs',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.EAST,
    colors: {
      primary: '#FCBA32',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/ohl/kingston-frontenacs.png',
  },
  {
    id: 'chl_ott',
    abbreviation: 'OTT',
    name: "Ottawa 67's",
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.EAST,
    colors: {
      primary: '#AC1F2D',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/ohl/ottawa-67s.svg',
  },
  {
    id: 'chl_pet',
    abbreviation: 'PET',
    name: 'Peterborough Petes',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.EAST,
    colors: {
      primary: '#94002A',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/ohl/peterborough-petes.svg',
  },
  {
    id: 'chl_sud',
    abbreviation: 'SUD',
    name: 'Sudbury Wolves',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.CENTRAL,
    colors: {
      primary: '#231F20',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/ohl/sudbury-wolves.svg',
  },

  // Central Division
  {
    id: 'chl_bar',
    abbreviation: 'BAR',
    name: 'Barrie Colts',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.CENTRAL,
    colors: {
      primary: '#FFD548',
      secondary: '#EC1B02',
    },
    logo_path: '/team_logos/chl/ohl/barrie-colts.svg',
  },
  {
    id: 'chl_brp',
    abbreviation: 'BRP',
    name: 'Bramptom Steelheads',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.CENTRAL,
    colors: {
      primary: '#1A2857',
      secondary: '#8F9090',
    },
    logo_path: '/team_logos/chl/ohl/brampton-steelheads.png',
  },
  {
    id: 'chl_nia',
    abbreviation: 'NIA',
    name: 'Niagara IceDogs',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.CENTRAL,
    colors: {
      primary: '#BF0C26',
      secondary: '#4C4E52',
    },
    logo_path: '/team_logos/chl/ohl/niagara-icedogs.svg',
  },
  {
    id: 'chl_nb',
    abbreviation: 'NB',
    name: 'North Bay Battalion',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.CENTRAL,
    colors: {
      primary: '#807A11',
      secondary: '#ED192D',
    },
    logo_path: '/team_logos/chl/ohl/north-bay-battalion.svg',
  },
  {
    id: 'chl_osh',
    abbreviation: 'OSH',
    name: 'Oshawa Generals',
    league: CHLLeague.OHL,
    conference: OHLConference.EASTERN,
    division: OHLDivision.EAST,
    colors: {
      primary: '#E21836',
      secondary: '#002D62',
    },
    logo_path: '/team_logos/chl/ohl/oshawa-generals.svg',
  },

  // Midwest Division
  {
    id: 'chl_eri',
    abbreviation: 'ERI',
    name: 'Erie Otters',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.MIDWEST,
    colors: {
      primary: '#FEC52F',
      secondary: '#0A1E3F',
    },
    logo_path: '/team_logos/chl/ohl/erie-otters.svg',
  },
  {
    id: 'chl_gue',
    abbreviation: 'GUE',
    name: 'Guelph Storm',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.MIDWEST,
    colors: {
      primary: '#900027',
      secondary: '#B3B5B8',
    },
    logo_path: '/team_logos/chl/ohl/guelph-storm.svg',
  },
  {
    id: 'chl_kit',
    abbreviation: 'KIT',
    name: 'Kitchener Rangers',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.MIDWEST,
    colors: {
      primary: '#CF0A2C',
      secondary: '#0033A0',
    },
    logo_path: '/team_logos/chl/ohl/kitchener-rangers.svg',
  },
  {
    id: 'chl_ldn',
    abbreviation: 'LND',
    name: 'London Knights',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.MIDWEST,
    colors: {
      primary: '#27824D',
      secondary: '#FEB81C',
    },
    logo_path: '/team_logos/chl/ohl/london-knights.svg',
  },
  {
    id: 'chl_os',
    abbreviation: 'OS',
    name: 'Owen Sound Attack',
    league: CHLLeague.OHL,
    division: OHLDivision.NORTH,
    colors: {
      primary: '#FFDD00',
      secondary: '#E03A3E',
    },
    logo_path: '/team_logos/chl/ohl/owen-sound-attack.svg',
  },

  // West Division
  {
    id: 'chl_fnt',
    abbreviation: 'FNT',
    name: 'Flint Firebirds',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.WEST,
    colors: {
      primary: '#0C1D3C',
      secondary: '#FC5D00',
    },
    logo_path: '/team_logos/chl/ohl/flint-firebirds.svg',
  },
  {
    id: 'chl_sag',
    abbreviation: 'SAG',
    name: 'Saginaw Spirit',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.WEST,
    colors: {
      primary: '#003263',
      secondary: '#BE2F38',
    },
    logo_path: '/team_logos/chl/ohl/saginaw-spirit.svg',
  },
  {
    id: 'chl_sar',
    abbreviation: 'SAR',
    name: 'Sarnia Sting',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.WEST,
    colors: {
      primary: '#FFC425',
      secondary: '#231F20',
    },
    logo_path: '/team_logos/chl/ohl/sarnia-sting.svg',
  },
  {
    id: 'chl_soo',
    abbreviation: 'SOO',
    name: 'Sault Ste. Marie Greyhounds',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.WEST,
    colors: {
      primary: '#CF2029',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/chl/ohl/soo-greyhounds.svg',
  },
  {
    id: 'chl_wsr',
    abbreviation: 'WSR',
    name: 'Windsor Spitfires',
    league: CHLLeague.OHL,
    conference: OHLConference.WESTERN,
    division: OHLDivision.WEST,
    colors: {
      primary: '#00274D',
      secondary: '#E31B23',
    },
    logo_path: '/team_logos/chl/ohl/windsor-spitfires.svg',
  },

  // QMJHL Teams
  // East Division
  {
    id: 'chl_bat',
    abbreviation: 'BAT',
    name: 'Acadie-Bathurst Titan',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.MARITIMES,
    colors: {
      primary: '#CFAA79',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/qmjhl/acadie-bathurst-titan.png',
  },
  {
    id: 'chl_cbe',
    abbreviation: 'CBE',
    name: 'Cape Breton Eagles',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.MARITIMES,
    colors: {
      primary: '#FAB406',
      secondary: '#23282B',
    },
    logo_path: '/team_logos/chl/qmjhl/cape-breton-eagles.jpg',
  },
  {
    id: 'chl_cha',
    abbreviation: 'CHA',
    name: 'Charlottetown Islanders',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.MARITIMES,
    colors: {
      primary: '#A8996E',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/qmjhl/charlottetown-islanders.png',
  },
  {
    id: 'chl_hal',
    abbreviation: 'HAL',
    name: 'Halifax Mooseheads',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.MARITIMES,
    colors: {
      primary: '#006F51',
      secondary: '#E31837',
    },
    logo_path: '/team_logos/chl/qmjhl/halifax-mooseheads.png',
  },
  {
    id: 'chl_sjd',
    abbreviation: 'SJD',
    name: 'Saint John Sea Dogs',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.MARITIMES,
    colors: {
      primary: '#B1B6BD',
      secondary: '#4274A6',
    },
    logo_path: '/team_logos/chl/qmjhl/saint-john-seadogs.svg',
  },

  // Central Division
  {
    id: 'chl_bcd',
    abbreviation: 'BCD',
    name: 'Baie-Comeau Drakkar',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.EAST,
    colors: {
      primary: '#FFCC02',
      secondary: '#EC1C24',
    },
    logo_path: '/team_logos/chl/qmjhl/baie-comeau-drakkar.svg',
  },
  {
    id: 'chl_chi',
    abbreviation: 'CHI',
    name: 'Chicoutimi Saguenéens',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.EAST,
    colors: {
      primary: '#3AB4E7',
      secondary: '#003263',
    },
    logo_path: '/team_logos/chl/qmjhl/chicoutimi-saguenens.svg',
  },
  {
    id: 'chl_que',
    abbreviation: 'QUE',
    name: 'Québec Remparts',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.EAST,
    colors: {
      primary: '#E31836',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/qmjhl/quebec-remparts.svg',
  },
  {
    id: 'chl_rim',
    abbreviation: 'RIM',
    name: 'Rimouski Océanic',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.EAST,
    colors: {
      primary: '#18124B',
      secondary: '#ABD8C0',
    },
    logo_path: '/team_logos/chl/qmjhl/rimouski-oceanic.png',
  },
  {
    id: 'chl_vic',
    abbreviation: 'VIC',
    name: 'Victoriaville Tigres',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.CENTRAL,
    colors: {
      primary: '#FCB827',
      secondary: '#EC1C2E',
    },
    logo_path: '/team_logos/chl/qmjhl/victoriaville-tigres.svg',
  },

  // West Division
  {
    id: 'chl_bba',
    abbreviation: 'BBA',
    name: 'Blainville-Boisbriand Armada',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.WEST,
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/chl/qmjhl/blainville-boisbriand-armada.svg',
  },
  {
    id: 'chl_dru',
    abbreviation: 'DRU',
    name: 'Drummondville Voltigeurs',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.CENTRAL,
    colors: {
      primary: '#EE3224',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/qmjhl/drummondville-voltigeurs.svg',
  },
  {
    id: 'chl_gat',
    abbreviation: 'GAT',
    name: 'Gatineau Olympiques',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.WEST,
    colors: {
      primary: '#717073',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/qmjhl/gatineau-olympiques.png',
  },
  {
    id: 'chl_rnh',
    abbreviation: 'RNH',
    name: 'Rouyn-Noranda Huskies',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.WEST,
    colors: {
      primary: '#ED1C2E',
      secondary: '#8E979D',
    },
    logo_path: '/team_logos/chl/qmjhl/rouyn-noranda-huskies.svg',
  },
  {
    id: 'chl_she',
    abbreviation: 'SHE',
    name: 'Sherbrooke Phoenix',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.CENTRAL,
    colors: {
      primary: '#051B54',
      secondary: '#F8F2D7',
    },
    logo_path: '/team_logos/chl/qmjhl/sherbrooke-phoenix.png',
  },
  {
    id: 'chl_vdo',
    abbreviation: 'VDO',
    name: "Val-d'Or Foreurs",
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.WEST,
    colors: {
      primary: '#DDB208',
      secondary: '#005941',
    },
    logo_path: '/team_logos/chl/qmjhl/val-d-or-foreurs.svg',
  },

  // WHL Teams
  // East Division
  {
    id: 'chl_bdn',
    abbreviation: 'BDN',
    name: 'Brandon Wheat Kings',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.EAST,
    colors: {
      primary: '#E6BF2E',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/whl/brandon-wheat-kings.svg',
  },
  {
    id: 'chl_mj',
    abbreviation: 'MJ',
    name: 'Moose Jaw Warriors',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.EAST,
    colors: {
      primary: '#CC0000',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/whl/moose-jaw-warriors.png',
  },
  {
    id: 'chl_pa',
    abbreviation: 'PA',
    name: 'Prince Albert Raiders',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.EAST,
    colors: {
      primary: '#0D843E',
      secondary: '#DAC796',
    },
    logo_path: '/team_logos/chl/whl/prince-albert-raiders.svg',
  },
  {
    id: 'chl_reg',
    abbreviation: 'REG',
    name: 'Regina Pats',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.EAST,
    colors: {
      primary: '#1A3668',
      secondary: '#EF3342',
    },
    logo_path: '/team_logos/chl/whl/regina-pats.svg',
  },
  {
    id: 'chl_sas',
    abbreviation: 'SAS',
    name: 'Saskatoon Blades',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.EAST,
    colors: {
      primary: '#FFCD36',
      secondary: '#262266',
    },
    logo_path: '/team_logos/chl/whl/saskatoon-blades.png',
  },
  {
    id: 'chl_sc',
    abbreviation: 'SC',
    name: 'Swift Current Broncos',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.EAST,
    colors: {
      primary: '#026937',
      secondary: '#001F5B',
    },
    logo_path: '/team_logos/chl/whl/swift-current-broncos.svg',
  },
  {
    id: 'chl_wnw',
    abbreviation: 'WNW',
    name: 'Wenatchee Wild',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.US,
    colors: {
      primary: '#002F87',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/chl/whl/wenatchee-wild.png',
  },

  // Central Division
  {
    id: 'chl_cgy',
    abbreviation: 'CGY',
    name: 'Calgary Hitmen',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.CENTRAL,
    colors: {
      primary: '#E13A3E',
      secondary: '#9E7053',
    },
    logo_path: '/team_logos/chl/whl/calgary-hitmen.svg',
  },
  {
    id: 'chl_edm',
    abbreviation: 'EDM',
    name: 'Edmonton Oil Kings',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.CENTRAL,
    colors: {
      primary: '#FFC42A',
      secondary: '#048743',
    },
    logo_path: '/team_logos/chl/whl/edmonton-oil-kings.svg',
  },
  {
    id: 'chl_lbg',
    abbreviation: 'LBG',
    name: 'Lethbridge Hurricanes',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.CENTRAL,
    colors: {
      primary: '#CC1D30',
      secondary: '#121942',
    },
    logo_path: '/team_logos/chl/whl/lethbridge-hurricanes.svg',
  },
  {
    id: 'chl_mh',
    abbreviation: 'MH',
    name: 'Medicine Hat Tigers',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.CENTRAL,
    colors: {
      primary: '#E56B1F',
      secondary: '#C03440',
    },
    logo_path: '/team_logos/chl/whl/medicine-hat-tigers.svg',
  },
  {
    id: 'chl_rd',
    abbreviation: 'RD',
    name: 'Red Deer Rebels',
    league: CHLLeague.WHL,
    conference: WHLConference.EASTERN,
    division: WHLDivision.CENTRAL,
    colors: {
      primary: '#900028',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/whl/red-deer-rebels.svg',
  },

  // B.C. Division
  {
    id: 'chl_kam',
    abbreviation: 'KAM',
    name: 'Kamloops Blazers',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.BC,
    colors: {
      primary: '#032C62',
      secondary: '#D0471D',
    },
    logo_path: '/team_logos/chl/whl/kamloops-blazers.png',
  },
  {
    id: 'chl_kel',
    abbreviation: 'KEL',
    name: 'Kelowna Rockets',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.BC,
    colors: {
      primary: '#008394',
      secondary: '#000000',
    },
    logo_path: '/team_logos/chl/whl/kelowna-rockets.svg',
  },
  {
    id: 'chl_pg',
    abbreviation: 'PG',
    name: 'Prince George Cougars',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.BC,
    colors: {
      primary: '#D0202E',
      secondary: '#D0A176',
    },
    logo_path: '/team_logos/chl/whl/prince-george-cougars.png',
  },
  {
    id: 'chl_van',
    abbreviation: 'VAN',
    name: 'Vancouver Giants',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.BC,
    colors: {
      primary: '#B5B7B9',
      secondary: '#97002E',
    },
    logo_path: '/team_logos/chl/whl/vancouver-giants.svg',
  },
  {
    id: 'chl_vic',
    abbreviation: 'VIC',
    name: 'Victoria Royals',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.BC,
    colors: {
      primary: '#013974',
      secondary: '#A4ADB4',
    },
    logo_path: '/team_logos/chl/whl/victoria-royals.png',
  },

  // U.S. Division
  {
    id: 'chl_eve',
    abbreviation: 'EVE',
    name: 'Everett Silvertips',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.US,
    colors: {
      primary: '#BC8448',
      secondary: '#045B41',
    },
    logo_path: '/team_logos/chl/whl/everett-silvertips.png',
  },
  {
    id: 'chl_por',
    abbreviation: 'POR',
    name: 'Portland Winterhawks',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.US,
    colors: {
      primary: '#CC202E',
      secondary: '#BE9D4D',
    },
    logo_path: '/team_logos/chl/whl/portland-winterhawks.svg',
  },
  {
    id: 'chl_sea',
    abbreviation: 'SEA',
    name: 'Seattle Thunderbirds',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.US,
    colors: {
      primary: '#003876',
      secondary: '#008357',
    },
    logo_path: '/team_logos/chl/whl/seattle-thunderbirds.svg',
  },
  {
    id: 'chl_spo',
    abbreviation: 'SPO',
    name: 'Spokane Chiefs',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.US,
    colors: {
      primary: '#C41230',
      secondary: '#013A81',
    },
    logo_path: '/team_logos/chl/whl/spokane-chiefs.svg',
  },
  {
    id: 'chl_tc',
    abbreviation: 'TC',
    name: 'Tri-City Americans',
    league: CHLLeague.WHL,
    conference: WHLConference.WESTERN,
    division: WHLDivision.US,
    colors: {
      primary: '#0D1D41',
      secondary: '#AC1A2D',
    },
    logo_path: '/team_logos/chl/whl/tri-city-americans.svg',
  },
  {
    id: 'chl_shc',
    abbreviation: 'SHC',
    name: 'Shawinigan Cataractes',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.WESTERN,
    division: QMJHLDivision.CENTRAL,
    colors: {
      primary: '#FFC425',
      secondary: '#98002E',
    },
    logo_path: '/team_logos/chl/qmjhl/shawinigan-cataractes.svg',
  },
  {
    id: 'chl_mnw',
    abbreviation: 'MNW',
    name: 'Moncton Wildcats',
    league: CHLLeague.QMJHL,
    conference: QMJHLConference.EASTERN,
    division: QMJHLDivision.MARITIMES,
    colors: {
      primary: '#FDC13D',
      secondary: '#D51E3C',
    },
    logo_path: '/team_logos/chl/qmjhl/moncton-wildcats.png',
  },
];
