import { ECHLTeam, ECHLDivision } from './types';

export const ECHL_TEAMS: ECHLTeam[] = [
  // North Division
  // {
  //   id: 'echl_nfl',
  //   abbreviation: 'NLG',
  //   name: 'Newfoundland Growlers',
  //   division: ECHLDivision.NORTH,
  //   nhlTeamId: 'tor',
  //   ahlTeamId: 'tor',
  //   colors: {
  //     primary: '#ad9567',
  //     secondary: '#000000',
  //   },
  },
  {
    id: 'echl_adk',
    abbreviation: 'ADK',
    name: 'Adirondack Thunder',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'njd',
    ahlTeamId: 'uti',
    colors: {
      primary: '#d2202f',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/ADK.svg',
  },
  {
    id: 'echl_mne',
    abbreviation: 'MNE',
    name: 'Maine Mariners',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'bos',
    ahlTeamId: 'pro',
    colors: {
      primary: '#203950',
      secondary: '#5fa853',
    },
    logo_path: '/team_logos/echl/MNE.svg',
  },
  {
    id: 'echl_nor',
    abbreviation: 'NOR',
    name: 'Norfolk Admirals',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'wpg',
    ahlTeamId: 'mb',
    colors: {
      primary: '#012369',
      secondary: '#fcc343',
    },
    logo_path: '/team_logos/echl/NOR.svg',
  },
  {
    id: 'echl_rea',
    abbreviation: 'REA',
    name: 'Reading Royals',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'phi',
    ahlTeamId: 'lhv',
    colors: {
      primary: '#634293',
      secondary: '#a8b1b7',
    },
    logo_path: '/team_logos/echl/REA.svg',
  },
  {
    id: 'echl_tr',
    abbreviation: 'TR',
    name: 'Trois-Rivières Lions',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'mtl',
    ahlTeamId: 'lav',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/TR.svg',
  },
  {
    id: 'echl_wor',
    abbreviation: 'WOR',
    name: 'Worcester Railers',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nyi',
    ahlTeamId: 'bri',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/WOR.svg',
  },

  // South Division
  {
    id: 'echl_atl',
    abbreviation: 'ATL',
    name: 'Atlanta Gladiators',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'ari',
    ahlTeamId: 'tuc',
    colors: {
      primary: '#081e3f',
      secondary: '#f8a01b',
    },
    logo_path: '/team_logos/echl/ATL.svg',
  },
  {
    id: 'echl_fla',
    abbreviation: 'FLA',
    name: 'Florida Everblades',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nsh',
    ahlTeamId: 'mil',
    colors: {
      primary: '#25315d',
      secondary: '#2c6956',
    },
    logo_path: '/team_logos/echl/FLA.svg',
  },
  {
    id: 'echl_gvl',
    abbreviation: 'GVL',
    name: 'Greenville Swamp Rabbits',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'lak',
    ahlTeamId: 'ont',
    colors: {
      primary: '#11244b',
      secondary: '#c06128',
    },
    logo_path: '/team_logos/echl/GVL.svg',
  },
  {
    id: 'echl_jax',
    abbreviation: 'JAX',
    name: 'Jacksonville Icemen',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nyr',
    ahlTeamId: 'hfd',
    colors: {
      primary: '#0c1e3f',
      secondary: '#9ca8b0',
    },
    logo_path: '/team_logos/echl/JAX.svg',
  },
  {
    id: 'echl_orl',
    abbreviation: 'ORL',
    name: 'Orlando Solar Bears',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'tbl',
    ahlTeamId: 'syr',
    colors: {
      primary: '#4b2a91',
      secondary: '#0088a7',
    },
    logo_path: '/team_logos/echl/ORL.svg',
  },
  {
    id: 'echl_sav',
    abbreviation: 'SAV',
    name: 'Savannah Ghost Pirates',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'vgk',
    ahlTeamId: 'hnd',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/SAV.svg',
  },
  {
    id: 'echl_sc',
    abbreviation: 'SC',
    name: 'South Carolina Stingrays',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'wsh',
    ahlTeamId: 'her',
    colors: {
      primary: '#003466',
      secondary: '#c4112f',
    },
    logo_path: '/team_logos/echl/SC.svg',
  },

  // // Central Division
  // {
  //   id: 'echl_qc',
  //   abbreviation: 'QC',
  //   name: 'Quad City Mallards',
  //   division: ECHLDivision.CENTRAL,
  //   nhlTeamId: 'stl',
  //   ahlTeamId: 'spr',
  //   colors: {
  //     primary: '#000000',
  //     secondary: '#FFFFFF',
  //   },
  // },
  {
    id: 'echl_blm',
    abbreviation: 'BLM',
    name: 'Bloomington Bison',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'car',
    ahlTeamId: 'chi',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/BLM.svg',
  },
  {
    id: 'echl_cin',
    abbreviation: 'CIN',
    name: 'Cincinnati Cyclones',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'buf',
    ahlTeamId: 'roc',
    colors: {
      primary: '#de0e2c',
      secondary: '#bfc0c1',
    },
    logo_path: '/team_logos/echl/CIN.svg',
  },
  {
    id: 'echl_fw',
    abbreviation: 'FW',
    name: 'Fort Wayne Komets',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'edm',
    ahlTeamId: 'bak',
    colors: {
      primary: '#ed5816',
      secondary: '#000000',
    },
    logo_path: '/team_logos/echl/FW.svg',
  },
  {
    id: 'echl_ind',
    abbreviation: 'IND',
    name: 'Indy Fuel',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'chi',
    ahlTeamId: 'rkf',
    colors: {
      primary: '#b92a30',
      secondary: '#ffc557',
    },
    logo_path: '/team_logos/echl/IND.svg',
  },
  {
    id: 'echl_ia',
    abbreviation: 'IA',
    name: 'Iowa Heartlanders',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'min',
    ahlTeamId: 'ia',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/IA.svg',
  },
  {
    id: 'echl_kal',
    abbreviation: 'KAL',
    name: 'Kalamazoo Wings',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'cbj',
    ahlTeamId: 'cle',
    colors: {
      primary: '#d82e3a',
      secondary: '#283c82',
    },
    logo_path: '/team_logos/echl/KAL.svg',
  },
  {
    id: 'echl_tol',
    abbreviation: 'TOL',
    name: 'Toledo Walleye',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'det',
    ahlTeamId: 'gr',
    colors: {
      primary: '#6799c8',
      secondary: '#ffc425',
    },
    logo_path: '/team_logos/echl/TOL.svg',
  },
  {
    id: 'echl_whl',
    abbreviation: 'WHL',
    name: 'Wheeling Nailers',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'pit',
    ahlTeamId: 'wbs',
    colors: {
      primary: '#b5a167',
      secondary: '#000000',
    },
    logo_path: '/team_logos/echl/WHL.svg',
  },

  // Mountain Division
  // {
  //   id: 'echl_ala',
  //   abbreviation: 'ALA',
  //   name: 'Alaska Aces',
  //   division: ECHLDivision.MOUNTAIN,
  //   nhlTeamId: 'van',
  //   ahlTeamId: 'abf',
  //   colors: {
  //     primary: '#000000',
  //     secondary: '#FFFFFF',
  //   },
  // },
  {
    id: 'echl_tah',
    abbreviation: 'TAH',
    name: 'Tahoe Knight Monsters',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'vgk',
    ahlTeamId: 'hnd',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/TAH.svg',
  },
  {
    id: 'echl_aln',
    abbreviation: 'ALN',
    name: 'Allen Americans',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'ott',
    ahlTeamId: 'bel',
    colors: {
      primary: '#bf1e2d',
      secondary: '#00153a',
    },
    logo_path: '/team_logos/echl/ALN.svg',
  },
  {
    id: 'echl_idh',
    abbreviation: 'IDH',
    name: 'Idaho Steelheads',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'dal',
    ahlTeamId: 'tex',
    colors: {
      primary: '#00457c',
      secondary: '#c3cdcf',
    },
    logo_path: '/team_logos/echl/IDH.svg',
  },
  {
    id: 'echl_kc',
    abbreviation: 'KC',
    name: 'Kansas City Mavericks',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'sea',
    ahlTeamId: 'cv',
    colors: {
      primary: '#5c9dbf',
      secondary: '#eb8c36',
    },
    logo_path: '/team_logos/echl/KC.svg',
  },
  {
    id: 'echl_rc',
    abbreviation: 'RC',
    name: 'Rapid City Rush',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'cgy',
    ahlTeamId: 'cgy',
    colors: {
      primary: '#a4162c',
      secondary: '#b4a66c',
    },
    logo_path: '/team_logos/echl/RC.svg',
  },
  {
    id: 'echl_tul',
    abbreviation: 'TUL',
    name: 'Tulsa Oilers',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'ana',
    ahlTeamId: 'sd',
    colors: {
      primary: '#111e3a',
      secondary: '#792131',
    },
    logo_path: '/team_logos/echl/TUL.svg',
  },
  {
    id: 'echl_uta',
    abbreviation: 'UTA',
    name: 'Utah Grizzlies',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'col',
    ahlTeamId: 'col',
    colors: {
      primary: '#00483a',
      secondary: '#a57a2f',
    },
    logo_path: '/team_logos/echl/UTA.svg',
  },
  {
    id: 'echl_wic',
    abbreviation: 'WIC',
    name: 'Wichita Thunder',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'sjs',
    ahlTeamId: 'sj',
    colors: {
      primary: '#0059ab',
      secondary: '#808588',
    },
    logo_path: '/team_logos/echl/WIC.svg',
  },
];
