import { ECHLTeam, ECHLDivision } from './types';

export const ECHL_TEAMS: ECHLTeam[] = [
  // North Division
  {
    id: 'echl_nf',
    abbreviation: 'NF',
    name: 'Newfoundland Growlers',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_car',
    ahlTeamId: 'ahl_chi',
    colors: {
      primary: '#ad9567',
      secondary: '#000000',
    },
    logo_path: '/team_logos/echl/NF.svg',
  },
  {
    id: 'echl_adk',
    abbreviation: 'ADK',
    name: 'Adirondack Thunder',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_njd',
    ahlTeamId: 'ahl_utc',
    colors: {
      primary: '#d2202f',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/ADK.svg',
  },
  {
    id: 'echl_mne',
    abbreviation: 'MNE',
    name: 'Maine Mariners',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_bos',
    ahlTeamId: 'ahl_pro',
    colors: {
      primary: '#203950',
      secondary: '#5fa853',
    },
    logo_path: '/team_logos/echl/MNE.svg',
  },
  {
    id: 'echl_nor',
    abbreviation: 'NOR',
    name: 'Norfolk Admirals',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_wpg',
    ahlTeamId: 'ahl_mb',
    colors: {
      primary: '#012369',
      secondary: '#fcc343',
    },
    logo_path: '/team_logos/echl/NOR.svg',
  },
  {
    id: 'echl_rea',
    abbreviation: 'REA',
    name: 'Reading Royals',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_phi',
    ahlTeamId: 'ahl_lhv',
    colors: {
      primary: '#634293',
      secondary: '#a8b1b7',
    },
    logo_path: '/team_logos/echl/REA.svg',
  },
  {
    id: 'echl_tr',
    abbreviation: 'TR',
    name: 'Trois-Rivières Lions',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_mtl',
    ahlTeamId: 'ahl_lav',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/TR.svg',
  },
  {
    id: 'echl_wor',
    abbreviation: 'WOR',
    name: 'Worcester Railers',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_nyi',
    ahlTeamId: 'ahl_bri',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/WOR.svg',
  },

  // South Division
  {
    id: 'echl_atl',
    abbreviation: 'ATL',
    name: 'Atlanta Gladiators',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_nsh',
    ahlTeamId: 'ahl_mil',
    colors: {
      primary: '#081e3f',
      secondary: '#f8a01b',
    },
    logo_path: '/team_logos/echl/ATL.svg',
  },
  {
    id: 'echl_fla',
    abbreviation: 'FLA',
    name: 'Florida Everblades',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_stl',
    ahlTeamId: 'ahl_spr',
    colors: {
      primary: '#25315d',
      secondary: '#2c6956',
    },
    logo_path: '/team_logos/echl/FLA.svg',
  },
  {
    id: 'echl_gvl',
    abbreviation: 'GVL',
    name: 'Greenville Swamp Rabbits',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_lak',
    ahlTeamId: 'ahl_ont',
    colors: {
      primary: '#11244b',
      secondary: '#c06128',
    },
    logo_path: '/team_logos/echl/GVL.svg',
  },
  {
    id: 'echl_jax',
    abbreviation: 'JAX',
    name: 'Jacksonville Icemen',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_buf',
    ahlTeamId: 'ahl_roc',
    colors: {
      primary: '#0c1e3f',
      secondary: '#9ca8b0',
    },
    logo_path: '/team_logos/echl/JAX.svg',
  },
  {
    id: 'echl_orl',
    abbreviation: 'ORL',
    name: 'Orlando Solar Bears',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_tbl',
    ahlTeamId: 'ahl_syr',
    colors: {
      primary: '#4b2a91',
      secondary: '#0088a7',
    },
    logo_path: '/team_logos/echl/ORL.svg',
  },
  {
    id: 'echl_sav',
    abbreviation: 'SAV',
    name: 'Savannah Ghost Pirates',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_fla',
    ahlTeamId: 'ahl_cha',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/SAV.svg',
  },
  {
    id: 'echl_sc',
    abbreviation: 'SC',
    name: 'South Carolina Stingrays',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.SOUTH,
    nhlTeamId: 'nhl_wsh',
    ahlTeamId: 'ahl_her',
    colors: {
      primary: '#003466',
      secondary: '#c4112f',
    },
    logo_path: '/team_logos/echl/SC.svg',
  },

  // Central Division
  {
    id: 'echl_qc',
    abbreviation: 'QC',
    name: 'Quad City Mallards',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_cbj',
    ahlTeamId: 'ahl_cle',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/QC.svg',
  },
  {
    id: 'echl_blm',
    abbreviation: 'BLM',
    name: 'Bloomington Bison',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_nyr',
    ahlTeamId: 'ahl_hfd',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/BLM.svg',
  },
  {
    id: 'echl_cin',
    abbreviation: 'CIN',
    name: 'Cincinnati Cyclones',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_tor',
    ahlTeamId: 'ahl_tor',
    colors: {
      primary: '#de0e2c',
      secondary: '#bfc0c1',
    },
    logo_path: '/team_logos/echl/CIN.svg',
  },
  {
    id: 'echl_fw',
    abbreviation: 'FW',
    name: 'Fort Wayne Komets',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_edm',
    ahlTeamId: 'ahl_bak',
    colors: {
      primary: '#ed5816',
      secondary: '#000000',
    },
    logo_path: '/team_logos/echl/FW.svg',
  },
  {
    id: 'echl_ind',
    abbreviation: 'IND',
    name: 'Indy Fuel',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_chi',
    ahlTeamId: 'ahl_rkf',
    colors: {
      primary: '#b92a30',
      secondary: '#ffc557',
    },
    logo_path: '/team_logos/echl/IND.svg',
  },
  {
    id: 'echl_ia',
    abbreviation: 'IA',
    name: 'Iowa Heartlanders',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_min',
    ahlTeamId: 'ahl_ia',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/IA.svg',
  },
  {
    id: 'echl_kal',
    abbreviation: 'KAL',
    name: 'Kalamazoo Wings',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_van',
    ahlTeamId: 'ahl_abb',
    colors: {
      primary: '#d82e3a',
      secondary: '#283c82',
    },
    logo_path: '/team_logos/echl/KAL.svg',
  },
  {
    id: 'echl_tol',
    abbreviation: 'TOL',
    name: 'Toledo Walleye',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.CENTRAL,
    nhlTeamId: 'nhl_det',
    ahlTeamId: 'ahl_gr',
    colors: {
      primary: '#6799c8',
      secondary: '#ffc425',
    },
    logo_path: '/team_logos/echl/TOL.svg',
  },
  {
    id: 'echl_whl',
    abbreviation: 'WHL',
    name: 'Wheeling Nailers',
    conference: ECHLConference.EASTERN,
    division: ECHLDivision.NORTH,
    nhlTeamId: 'nhl_pit',
    ahlTeamId: 'ahl_wbs',
    colors: {
      primary: '#b5a167',
      secondary: '#000000',
    },
    logo_path: '/team_logos/echl/WHL.svg',
  },

  // Mountain Division
  {
    id: 'echl_ala',
    abbreviation: 'ALA',
    name: 'Alaska Aces',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_uta',
    ahlTeamId: 'nhl_tuc',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/ALA.svg',
  },
  {
    id: 'echl_tah',
    abbreviation: 'TAH',
    name: 'Tahoe Knight Monsters',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_vgk',
    ahlTeamId: 'ahl_hnd',
    colors: {
      primary: '#000000',
      secondary: '#FFFFFF',
    },
    logo_path: '/team_logos/echl/TAH.svg',
  },
  {
    id: 'echl_aln',
    abbreviation: 'ALN',
    name: 'Allen Americans',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_ott',
    ahlTeamId: 'ahl_bel',
    colors: {
      primary: '#bf1e2d',
      secondary: '#00153a',
    },
    logo_path: '/team_logos/echl/ALN.svg',
  },
  {
    id: 'echl_idh',
    abbreviation: 'IDH',
    name: 'Idaho Steelheads',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_dal',
    ahlTeamId: 'ahl_tex',
    colors: {
      primary: '#00457c',
      secondary: '#c3cdcf',
    },
    logo_path: '/team_logos/echl/IDH.svg',
  },
  {
    id: 'echl_kc',
    abbreviation: 'KC',
    name: 'Kansas City Mavericks',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_sea',
    ahlTeamId: 'ahl_cv',
    colors: {
      primary: '#5c9dbf',
      secondary: '#eb8c36',
    },
    logo_path: '/team_logos/echl/KC.svg',
  },
  {
    id: 'echl_rc',
    abbreviation: 'RC',
    name: 'Rapid City Rush',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_cgy',
    ahlTeamId: 'ahl_cgy',
    colors: {
      primary: '#a4162c',
      secondary: '#b4a66c',
    },
    logo_path: '/team_logos/echl/RC.svg',
  },
  {
    id: 'echl_tul',
    abbreviation: 'TUL',
    name: 'Tulsa Oilers',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_ana',
    ahlTeamId: 'ahl_sd',
    colors: {
      primary: '#111e3a',
      secondary: '#792131',
    },
    logo_path: '/team_logos/echl/TUL.svg',
  },
  {
    id: 'echl_uta',
    abbreviation: 'UTA',
    name: 'Utah Grizzlies',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_col',
    ahlTeamId: 'ahl_col',
    colors: {
      primary: '#00483a',
      secondary: '#a57a2f',
    },
    logo_path: '/team_logos/echl/UTA.svg',
  },
  {
    id: 'echl_wic',
    abbreviation: 'WIC',
    name: 'Wichita Thunder',
    conference: ECHLConference.WESTERN,
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: 'nhl_sjs',
    ahlTeamId: 'ahl_sj',
    colors: {
      primary: '#0059ab',
      secondary: '#808588',
    },
    logo_path: '/team_logos/echl/WIC.svg',
  },
];
