import { ECHLTeam, ECHLDivision } from "./types";

export const ECHL_TEAMS: ECHLTeam[] = [
  // North Division
  {
    id: "adk",
    name: "Adirondack Thunder",
    division: ECHLDivision.NORTH,
    nhlTeamId: "njd",
    ahlTeamId: "uti",
  },
  {
    id: "mai",
    name: "Maine Mariners",
    division: ECHLDivision.NORTH,
    nhlTeamId: "bos",
    ahlTeamId: "pro",
  },
  {
    id: "nor",
    name: "Norfolk Admirals",
    division: ECHLDivision.NORTH,
    nhlTeamId: "wpg",
    ahlTeamId: "mb",
  },
  {
    id: "rea",
    name: "Reading Royals",
    division: ECHLDivision.NORTH,
    nhlTeamId: "phi",
    ahlTeamId: "lhv",
  },
  {
    id: "tro",
    name: "Trois-Rivières Lions",
    division: ECHLDivision.NORTH,
    nhlTeamId: "mtl",
    ahlTeamId: "lav",
  },
  {
    id: "wor",
    name: "Worcester Railers",
    division: ECHLDivision.NORTH,
    nhlTeamId: "nyi",
    ahlTeamId: "bri",
  },

  // South Division
  {
    id: "atl",
    name: "Atlanta Gladiators",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "ari",
    ahlTeamId: "tuc",
  },
  {
    id: "fla",
    name: "Florida Everblades",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "nsh",
    ahlTeamId: "mil",
  },
  {
    id: "grn",
    name: "Greenville Swamp Rabbits",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "lak",
    ahlTeamId: "ont",
  },
  {
    id: "jax",
    name: "Jacksonville Icemen",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "nyr",
    ahlTeamId: "hfd",
  },
  {
    id: "orl",
    name: "Orlando Solar Bears",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "tbl",
    ahlTeamId: "syr",
  },
  {
    id: "sav",
    name: "Savannah Ghost Pirates",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "vgk",
    ahlTeamId: "hnd",
  },
  {
    id: "sc",
    name: "South Carolina Stingrays",
    division: ECHLDivision.SOUTH,
    nhlTeamId: "wsh",
    ahlTeamId: "her",
  },

  // Central Division
  {
    id: "cin",
    name: "Cincinnati Cyclones",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "buf",
    ahlTeamId: "roc",
  },
  {
    id: "fw",
    name: "Fort Wayne Komets",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "edm",
    ahlTeamId: "bak",
  },
  {
    id: "ind",
    name: "Indy Fuel",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "chi",
    ahlTeamId: "rkf",
  },
  {
    id: "iowa",
    name: "Iowa Heartlanders",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "min",
    ahlTeamId: "ia",
  },
  {
    id: "kal",
    name: "Kalamazoo Wings",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "cbj",
    ahlTeamId: "cle",
  },
  {
    id: "tol",
    name: "Toledo Walleye",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "det",
    ahlTeamId: "gr",
  },
  {
    id: "whl",
    name: "Wheeling Nailers",
    division: ECHLDivision.CENTRAL,
    nhlTeamId: "pit",
    ahlTeamId: "wbs",
  },

  // Mountain Division
  {
    id: "all",
    name: "Allen Americans",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "ott",
    ahlTeamId: "bel",
  },
  {
    id: "idh",
    name: "Idaho Steelheads",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "dal",
    ahlTeamId: "tex",
  },
  {
    id: "kc",
    name: "Kansas City Mavericks",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "sea",
    ahlTeamId: "cv",
  },
  {
    id: "rc",
    name: "Rapid City Rush",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "cgy",
    ahlTeamId: "cgy",
  },
  {
    id: "tul",
    name: "Tulsa Oilers",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "ana",
    ahlTeamId: "sd",
  },
  {
    id: "uta",
    name: "Utah Grizzlies",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "col",
    ahlTeamId: "col",
  },
  {
    id: "wic",
    name: "Wichita Thunder",
    division: ECHLDivision.MOUNTAIN,
    nhlTeamId: "sjs",
    ahlTeamId: "sj",
  },
]; 